### PR TITLE
hide sidedock when empty

### PR DESCRIPTION
**Pull request by Licini**
This thing has been driving me crazy...Just a quick fix/hack to automatically hide the sidedock when it is empty. The proper way is to use the config which is not yet implemented. 

@tomvanmele I would also like to discuss about the these config class. Have the feeling it got over-complicated should be simplified

### CODE REVIEW

**Comment by tomvanmele** [comment]
i am not really interested in a quick fix. first of all, the basic profile should not have any additional UI elements. secondly, this should simply be a config setting...

**Comment by Licini** [comment]
> i am not really interested in a quick fix. first of all, the basic profile should not have any additional UI elements. secondly, this should simply be a config setting...

ok... then maybe this first #108

**Comment by Licini** [comment]
@tomvanmele Brought this back.

**Comment by tomvanmele** [comment]
dunno. to me this issue seems a bit redundant because we a re switching to fixed UI areas instead of side docks. perhaps once we have the fixed areas under control we can revive the existence of side docks...

**Pull request closed without merging**
