### PR TITLE
update mouse buttons

### PR DESCRIPTION
**Pull request by Licini**
#71 Would prefer this also for 3D views, let me know what you guys think

### CODE REVIEW

**Comment by tomvanmele** [comment]
in principle i have no real preference.

however, the buttons should be intuitive. when i user Blender, for example, it always takes me a few tries to find the right button to rotate or pan. in Rhino and the current viewer i don't have this...

**Comment by Licini** [comment]
@PingHsunTsai how about your vote?

**Comment by PingHsunTsai** [comment]
@Licini personally I'm used to rhino setting, but as tom said we can always adapt

**Review by PingHsunTsai — APPROVED** [review]

**Review by tomvanmele — APPROVED** [review]

**Comment by Licini** [comment]
yep, let's see how does this setup feel, if everybody feels weird we revert back : ) @tomvanmele @PingHsunTsai

**Pull request merged**
