### PR TITLE
add on method

### PR DESCRIPTION
**Pull request by PingHsunTsai**
### What type of change is this?

- [ ] add `Viewer.on` feature.

### CODE REVIEW

**Comment by tomvanmele** [comment]
@Licini could you have a look at this please and merge and release if ok?

**Comment by Licini** [comment]
@PingHsunTsai the old dynamic mesh is not a very good example script, I updated it a bit.

**Comment by Licini** [comment]
@PingHsunTsai is this ready or you are still working on it?

**Comment by PingHsunTsai** [comment]
@Licini  I'm simplifying it, a sec

**Pull request merged**
