### PR TITLE
Feature/Layout

### PR DESCRIPTION
**Pull request by ZacZhangzhuo**
## Review Points
- basic layout elements: `MenubarLayout`, `ToolbarLayout`, `StatusbarLayout`,`SidedockLayout`.

## Major Changes
* Added basic layout elements: `MenubarLayout`, `ToolbarLayout`, `StatusbarLayout`,`SidedockLayout`.
* Documentation improved.

## Test Files

```python
from compas_viewer import Viewer
viewer = Viewer()
viewer.show()
```
image

## Doc builds

|    |    |
|  ----  |   ---- |
|    |    |
|  |   |

Feel free to comment! I will go ahead for the `tree view`.

### CODE REVIEW

**Comment by tomvanmele** [comment]
> Function wise I think it's good, but I'm not a big fan of how these buttons look like ... @tomvanmele Any opinions?

no we should use icons for this. an older version of view2 already had this so the infrastructure should be there. i think it is as simple as specifying `QIcon` or something like that...

**Comment by ZacZhangzhuo** [comment]
> > Function wise I think it's good, but I'm not a big fan of how these buttons look like ... @tomvanmele Any opinions?
> 
> no we should use icons for this. an older version of view2 already had this so the infrastructure should be there. i think it is as simple as specifying `QIcon` or something like that...

yes yes, that is what I thought too, I just used the buttons as a temporary thing as I cannot find good icons...

**Comment by tomvanmele** [comment]
https://fontawesome.com/search?q=zoom&o=r

**Comment by tomvanmele** [comment]
> https://fontawesome.com/search?q=zoom&o=r

i have a professional account if needed...

**Comment by ZacZhangzhuo** [comment]
updated also with simple slider implementation:

image

**Pull request merged**
