### PR TITLE
obj info

### PR DESCRIPTION
**Pull request by PingHsunTsai**
### What type of change is this?

- [ ] Added `object_info_cmd` for `compas_viewer.commends`.

obj_setting_0

obj_setting_1

### CODE REVIEW

**Comment by Licini** [comment]
@tomvanmele Didn't we want to show these kind of information at the lower half of right side bar? Or is this a feature that you requested?

**Comment by PingHsunTsai** [comment]
I think the idea is have them at both :) I will implement it in the sidebar as well

**Comment by tomvanmele** [comment]
i would like to have this in the default bottom slot of the sidebar on the right indeed. doesn't hurt to have it as a popup as well. either way, i would like to see this information a bit more organised though. for example in a table. and it should be modifiable...

**Comment by PingHsunTsai** [comment]
now the object setting is both in sidebar and menu, will update them to config once #169 is finished!

**Pull request merged**
